In [1]:
#import all your libraries you need
#recommend using aliases for NumPy and Pandas

from matplotlib import dates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yfinance as yf

In [2]:
raw = yf.download('SPY AAPL', start= '2010-01-01', end='2019-12-31')

[*********************100%***********************]  1 of 2 completed

In [3]:
raw

Price           Close                   High                    Low  \
Ticker           AAPL         SPY       AAPL         SPY       AAPL
Date
2010-01-04   6.406481   84.578491   6.421150   84.623268   6.357687
2010-01-05   6.417555   84.802353   6.453777   84.839670   6.383727
2010-01-06   6.315478   84.862053   6.443003   85.071017   6.308892
2010-01-07   6.303801   85.220284   6.346310   85.324765   6.258000
2010-01-08   6.345711   85.503891   6.346310   85.541208   6.258301
...               ...         ...        ...         ...        ...
2019-12-23  68.396278  292.798279  68.456486  293.190225  67.522057
2019-12-24  68.461304  292.807404  68.610626  293.071724  68.136186
2019-12-26  69.819595  294.366089  69.836455  294.375213  68.564863
2019-12-27  69.793076  294.293182  70.797348  295.150013  69.388480
2019-12-30  70.207306  292.670624  70.489082  294.511911  68.690068

Price                        Open                 Volume
Ticker             SPY       AAPL         SPY       AAPL        SPY
Date
2010-01-04   83.220220   6.389119   83.862041  493729600  118944600
2010-01-05   84.220238   6.424141   84.526225  601904800  111579900
2010-01-06   84.653089   6.417558   84.720254  552160000  116074400
2010-01-07   84.466516   6.338826   84.705333  477131200  131091100
2010-01-08   84.824759   6.295420   84.996405  447610800  126402800
...                ...        ...         ...        ...        ...
2019-12-23  292.652432  67.560591  293.135537   98572000   52990000
2019-12-24  292.506587  68.562456  293.026159   48478800   20270000
2019-12-26  293.181125  68.593762  293.190221   93121200   30911200
2019-12-27  293.764513  70.110975  295.095324  146266000   42528800
2019-12-30  292.187520  69.711193  294.375188  144114400   49729100

[2515 rows x 10 columns]

In [4]:
raw.columns

MultiIndex([( 'Close', 'AAPL'),
            ( 'Close',  'SPY'),
            (  'High', 'AAPL'),
            (  'High',  'SPY'),
            (   'Low', 'AAPL'),
            (   'Low',  'SPY'),
            (  'Open', 'AAPL'),
            (  'Open',  'SPY'),
            ('Volume', 'AAPL'),
            ('Volume',  'SPY')],
           names=['Price', 'Ticker'])

In [ ]:
#Going to use the .pipe method a lot
#use the syntax below to pull up the docs for a certain function or method
raw.pipe?

Signature:
raw.pipe(
    func: 'Callable[..., T] | tuple[Callable[..., T], str]',
    *args,
    **kwargs,
) -> 'T'
Docstring:
Apply chainable functions that expect Series or DataFrames.

Parameters
----------
func : function
    Function to apply to the Series/DataFrame.
    ``args``, and ``kwargs`` are passed into ``func``.
    Alternatively a ``(callable, data_keyword)`` tuple where
    ``data_keyword`` is a string indicating the keyword of
    ``callable`` that expects the Series/DataFrame.
*args : iterable, optional
    Positional arguments passed into ``func``.
**kwargs : mapping, optional
    A dictionary of keyword arguments passed into ``func``.

Returns
-------
the return type of ``func``.

See Also
--------
DataFrame.apply : Apply a function along input axis of DataFrame.
DataFrame.map : Apply a function elementwise on a whole DataFrame.
Series.map : Apply a mapping correspondence on a
    :class:`~pandas.Series`.

Notes
-----
Use ``.pipe`` when chaining together functions that expect
Series, DataFrames or GroupBy objects.

Examples
--------
Constructing a income DataFrame from a dictionary.

>>> data = [[8000, 1000], [9500, np.nan], [5000, 2000]]
>>> df = pd.DataFrame(data, columns=['Salary', 'Others'])
>>> df
   Salary  Others
0    8000  1000.0
1    9500     NaN
2    5000  2000.0

Functions that perform tax reductions on an income DataFrame.

>>> def subtract_federal_tax(df):
...     return df * 0.9
>>> def subtract_state_tax(df, rate):
...     return df * (1 - rate)
>>> def subtract_national_insurance(df, rate, rate_increase):
...     new_rate = rate + rate_increase
...     return df * (1 - new_rate)

Instead of writing

>>> subtract_national_insurance(
...     subtract_state_tax(subtract_federal_tax(df), rate=0.12),
...     rate=0.05,
...     rate_increase=0.02)  # doctest: +SKIP

You can write

>>> (
...     df.pipe(subtract_federal_tax)
...     .pipe(subtract_state_tax, rate=0.12)
...     .pipe(subtract_national_insurance, rate=0.05, rate_increase=0.02)
... )
    Salary   Others
0  5892.48   736.56
1  6997.32      NaN
2  3682.80  1473.12

If you have a function that takes the data as (say) the second
argument, pass a tuple indicating which keyword expects the
data. For example, suppose ``national_insurance`` takes its data as ``df``
in the second argument:

>>> def subtract_national_insurance(rate, df, rate_increase):
...     new_rate = rate + rate_increase
...     return df * (1 - new_rate)
>>> (
...     df.pipe(subtract_federal_tax)
...     .pipe(subtract_state_tax, rate=0.12)
...     .pipe(
...         (subtract_national_insurance, 'df'),
...         rate=0.05,
...         rate_increase=0.02
...     )
... )
    Salary   Others
0  5892.48   736.56
1  6997.32      NaN
2  3682.80  1473.12
File:      c:\users\schuspe\appdata\roaming\python\python313\site-packages\pandas\core\generic.py
Type:      method

In [ ]:
#youtube videos demonstrating and explaing pipe .pipe(fix_cols)
#iloc is a selector that selects rows and columns based on index position


def fix_cols(df):
    columns = df.columns
    outer = [col[0] for col in columns]
    df.columns = outer
    return df
(raw
 .iloc[:, ::2]
 .pipe(fix_cols)
)

                Close       High        Low       Open     Volume
Date
2010-01-04   6.406481   6.421150   6.357687   6.389119  493729600
2010-01-05   6.417555   6.453777   6.383727   6.424141  601904800
2010-01-06   6.315478   6.443003   6.308892   6.417558  552160000
2010-01-07   6.303801   6.346310   6.258000   6.338826  477131200
2010-01-08   6.345711   6.346310   6.258301   6.295420  447610800
...               ...        ...        ...        ...        ...
2019-12-23  68.396278  68.456486  67.522057  67.560591   98572000
2019-12-24  68.461304  68.610626  68.136186  68.562456   48478800
2019-12-26  69.819595  69.836455  68.564863  68.593762   93121200
2019-12-27  69.793076  70.797348  69.388480  70.110975  146266000
2019-12-30  70.207306  70.489082  68.690068  69.711193  144114400

[2515 rows x 5 columns]

In [ ]:


#tweak_data helps clean data and see steps used to clean data

import yfinance as yf

def fix_cols(df):
    columns = df.columns
    outer = [col[0] for col in columns]
    df.columns = outer
    return df

def tweak_data():
    raw = yf.download('SPY AAPL', start='2010-01-01', end= '2019-12-31')

    return (raw
            .iloc[:, ::2]
            .pipe(fix_cols)
    )

tweak_data()

[*********************100%***********************]  2 of 2 completed

                Close       High        Low       Open     Volume
Date
2010-01-04   6.406481   6.421149   6.357686   6.389118  493729600
2010-01-05   6.417556   6.453778   6.383729   6.424142  601904800
2010-01-06   6.315475   6.443000   6.308890   6.417555  552160000
2010-01-07   6.303801   6.346310   6.258000   6.338826  477131200
2010-01-08   6.345711   6.346310   6.258300   6.295419  447610800
...               ...        ...        ...        ...        ...
2019-12-23  68.396263  68.456471  67.522042  67.560576   98572000
2019-12-24  68.461288  68.610610  68.136171  68.562441   48478800
2019-12-26  69.819595  69.836455  68.564863  68.593762   93121200
2019-12-27  69.793098  70.797371  69.388503  70.110998  146266000
2019-12-30  70.207352  70.489128  68.690113  69.711238  144114400

[2515 rows x 5 columns]